import {test} from 'node:test';
import assert from 'node:assert/strict';
import {RepCounter,angle} from '../dist/engine.js';
test('joint angle geometry',()=>{assert.equal(angle({x:0,y:0},{x:0,y:1},{x:1,y:1}),90);assert.equal(angle({x:0,y:0},{x:0,y:1},{x:0,y:2}),180);assert.ok(Number.isNaN(angle({x:0,y:0},{x:0,y:0},{x:1,y:0})));});
for(const [name,low]of [['squat',80],['curl',30],['pushup',80]]){test(name+' counts full stable cycles, rejects partials and tracking loss',()=>{const c=new RepCounter(name);let t=0;function hold(a,conf=.99,frames=25){for(let i=0;i<frames;i++)c.update(a,conf,t+=40);}hold(low);hold(170);assert.equal(c.reps,0,'starting bent does not count');hold(125);hold(170);assert.equal(c.reps,0,'partial does not count');hold(low);hold(170);assert.equal(c.reps,1);hold(170);assert.equal(c.reps,1,'holding top does not double-count');hold(low);hold(low,0);hold(170);assert.equal(c.reps,1,'occlusion invalidates cycle');hold(low);hold(170);assert.equal(c.reps,2);});}
test('single-frame spikes cannot count reps',()=>{const c=new RepCounter('squat');for(let t=0;t<3000;t+=40)c.update(t%80?80:170,.99,t);assert.equal(c.reps,0);});
for(const fps of [15,30,60])test(`continuous squats count at ${fps} fps without holding endpoints`,()=>{const c=new RepCounter('squat');const dt=1000/fps;for(let t=0;t<=6800;t+=dt){const a=155-48*(1-Math.cos(2*Math.PI*t/2200))/2;c.update(a,.9,t);}assert.equal(c.reps,3);});
test('brief confidence flicker preserves a squat, sustained loss invalidates it',()=>{const c=new RepCounter('squat');let t=0;const hold=(a,confidence,frames)=>{for(let i=0;i<frames;i++)c.update(a,confidence,t+=40);};hold(155,.9,20);hold(108,.9,20);hold(108,.1,3);assert.equal(c.reps,0);hold(108,.9,8);hold(155,.9,20);assert.equal(c.reps,1);hold(108,.9,20);hold(108,.1,15);hold(155,.9,20);assert.equal(c.reps,1);});
test('a long gap with no frames invalidates the partial cycle',()=>{const c=new RepCounter('squat');for(let t=0;t<1000;t+=40)c.update(155,.9,t);for(let t=1000;t<2000;t+=40)c.update(108,.9,t);for(let t=4000;t<5000;t+=40)c.update(155,.9,t);assert.equal(c.reps,0);});
