from pathlib import Path
p=Path('dist/index.html');s=p.read_text(encoding='utf-8')
s=s.replace('<span id="set-note">','<span id="set-note">',1).replace('<div class="metrics">','<section id="readiness-panel" class="readiness-panel" hidden aria-live="polite"><strong id="readiness-title">Camera position check</strong><p id="readiness-text">Show the required joints and hold your start position.</p><progress id="readiness-progress" max="1" value="0" aria-label="Camera readiness"></progress></section><div class="metrics">',1)
s=s.replace('<button id="next-set"', '<span id="rest-countdown" hidden></span><button id="next-set"',1)
s=s.replace('<label class="field-label" for="voice-select">','<label class="field-label" for="rest-seconds">Rest between sets <span>seconds</span></label><input id="rest-seconds" class="rest-input" type="number" min="0" max="300" step="5" value="30"><p class="tiny">The next set starts only when you choose. Use 0 for no countdown.</p><label class="field-label" for="voice-select">',1)
s=s.replace('<p class="tiny" id="voice-note"></p>','<p class="tiny" id="voice-note" role="status"></p><label class="offline-voice-filter"><input id="offline-voices" type="checkbox"> Show offline voices only</label><button id="reload-voices" class="text-button">Refresh voice list</button>',1)
s=s.replace('<div id="history-summary" class="history-summary"></div>', '<h2 class="progress-title">Your last 7 days</h2><p class="tiny">Live workouts only. Demo sessions remain in the table below.</p><div id="history-summary" class="history-summary"></div><div id="weekly-chart" class="weekly-chart" aria-label="Workouts in the last seven days"></div>')
s=s.replace('<small>Download once with internet.', '<progress id="offline-progress" max="100" value="0" hidden aria-label="Offline download progress"></progress><small>Saved inside this browser, not as a file. Download once with internet.')
p.write_text(s,encoding='utf-8')
p=Path('dist/app.js');s=p.read_text(encoding='utf-8');s="import {ReadinessGate,RestTimer,weeklyProgress} from './training.js';\n"+s
s=s.replace('let completedSets=[]',"const readiness=new ReadinessGate(),rest=new RestTimer();\nlet checkingCamera=false;\nlet completedSets=[]",1)
s=s.replace("const list=speechSynthesis.getVoices().filter(v=>navigator.onLine||v.localService)","const list=speechSynthesis.getVoices().filter(v=>(navigator.onLine&&!$('offline-voices').checked)||v.localService)")
s=s.replace("v.localService?' · offline':''", "v.localService?' · offline':' · internet required'")
s=s.replace("$('voice-note').textContent='Choose any installed male or female voice. Voices marked offline work without internet. Other voices may need a connection.';", "if(!$('voice-select').value){const local=list.find(v=>v.localService&&v.lang.startsWith('en'))||list.find(v=>v.localService);if(local)$('voice-select').value=local.name;}$('voice-note').textContent=list.length?`${list.length} voices available. Preview a voice to hear it. Offline voices run on your device.`:'No matching voices found. Install a speech voice in your device language settings, then refresh this list. Written coaching still works.';")
s=s.replace("u.voice=speechSynthesis.getVoices().find(v=>v.name===$('voice-select').value)||null;", "u.voice=speechSynthesis.getVoices().find(v=>v.name===$('voice-select').value)||(!navigator.onLine?speechSynthesis.getVoices().find(v=>v.localService):null)||null;")
s=s.replace("u.onerror=()=>toast('Voice could not play. Try another installed voice.');", "u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('Voice could not play. Try another installed voice.');};")
s=s.replace("exercise=key;completedSets", "exercise=key;rest.clear();$('rest-countdown').hidden=true;completedSets",1)
s=s.replace("function completeSet(){if(betweenSets)return;", "function completeSet(){if(betweenSets)return;",1)
s=s.replace("betweenSets=true;paused=true;", "betweenSets=true;paused=true;checkingCamera=false;$('readiness-panel').hidden=true;rest.start(completedSets.length<setCount()?Number($('rest-seconds').value):0,performance.now());",1)
s=s.replace("betweenSets=false;paused=false;demoTime=0;", "betweenSets=false;paused=false;rest.clear();$('rest-countdown').hidden=true;startReadiness();demoTime=0;",1)
s=s.replace("mode=source;paused=false;", "mode=source;paused=false;rest.clear();$('rest-countdown').hidden=true;startReadiness();$('rest-seconds').disabled=true;",1)
s=s.replace("mode=null;paused=false;", "mode=null;paused=false;checkingCamera=false;rest.clear();$('rest-countdown').hidden=true;$('readiness-panel').hidden=true;$('rest-seconds').disabled=false;",1)
s=s.replace("paused=!paused;counter.resetCycle();", "paused=!paused;counter.resetCycle();if(!paused)startReadiness();",1)
s=s.replace("function processPose(points,now)", "function startReadiness(){readiness.reset();checkingCamera=mode==='camera';$('readiness-panel').hidden=!checkingCamera;$('readiness-progress').value=0;$('readiness-title').textContent='Camera position check';$('readiness-text').textContent=EXERCISES[exercise].setup;}\nfunction updateRest(now){if(!mode||!betweenSets||completedSets.length>=setCount())return;const remaining=rest.remaining(now);$('rest-countdown').hidden=false;$('rest-countdown').textContent=remaining?`Rest ${timeText(remaining*1000)}`:'Rest complete';$('next-set').textContent=remaining?'Skip rest & start next set':'Start next set';if(!remaining&&!rest.announced){rest.announced=true;lastSpeak=-Infinity;feedback('Rest complete. Start the next set when you are ready.',true);}}\nfunction processPose(points,now)",1)
s=s.replace("if(!points){counter.update", "if(!points){if(checkingCamera){readiness.update(false,now);$('readiness-progress').value=0;$('readiness-text').textContent='No person detected. Move into the frame with your full body visible.';}counter.update",1)
s=s.replace("const counted=counter.update(deg,conf,now);", "if(checkingCamera){const startValid=conf>=.65&&deg>=(exercise==='plank'?160:cfg.up);const ready=readiness.update(startValid,now);drawPose(points,conf,ids);renderMetrics(conf);$('readiness-progress').value=readiness.progress(now);$('readiness-text').textContent=conf<.65?'Show all required joints. Move back, improve lighting, and follow the camera view in the form tips.':!startValid?'Joints visible. '+cfg.setup:'Start position found. Hold steady for a moment.';$('tracking-status').textContent='Checking camera position';if(!ready)return;checkingCamera=false;counter.resetCycle();$('readiness-title').textContent='Ready to train';$('readiness-text').textContent='Required joints and start position checked. Begin your set.';lastSpeak=-Infinity;feedback('Position ready. Begin your set.',true);return;}const counted=counter.update(deg,conf,now);",1)
s=s.replace("lastTick=now;if(mode&&!paused){elapsed+=dt;", "lastTick=now;updateRest(now);if(mode&&!paused){if(!checkingCamera)elapsed+=dt;",1)
a=s.index("function renderHistory(){");b=s.index("$('history-empty')",a)
s=s[:a]+"function renderHistory(){const week=weeklyProgress(history);$('history-summary').replaceChildren(...[[week.sessions,'Workouts'],[week.sets,'Completed sets'],[week.reps,'Repetitions'],[week.holds+'s','Plank holds']].map(([n,label])=>{const a=document.createElement('article'),b=document.createElement('strong'),s=document.createElement('span');b.textContent=n;s.textContent=label;a.append(b,s);return a;}));const max=Math.max(1,...week.days.map(d=>d.sessions));$('weekly-chart').replaceChildren(...week.days.map(d=>{const a=document.createElement('div'),bar=document.createElement('div'),label=document.createElement('span');a.className='weekly-day';bar.className='weekly-bar';bar.style.height=(8+d.sessions/max*90)+'px';bar.textContent=d.sessions;label.textContent=d.label;a.setAttribute('aria-label',d.label+': '+d.sessions+' workouts');a.append(bar,label);return a;}));"+s[b:]
s += "\n$('offline-voices').onchange=voices;$('reload-voices').onclick=voices;$('rest-seconds').onchange=()=>{$('rest-seconds').value=Math.max(0,Math.min(300,Math.round(Number($('rest-seconds').value)||0)));};\n"
p.write_text(s,encoding='utf-8')
p=Path('dist/styles.css');s=p.read_text(encoding='utf-8');s+='''
.readiness-panel{margin-top:16px;padding:18px;border:1px solid #70885a;border-radius:10px;background:#203123}.readiness-panel p{font-size:14px;line-height:1.6}.readiness-panel progress,#offline-progress{width:100%;accent-color:var(--green)}#rest-countdown{font-variant-numeric:tabular-nums;color:var(--green);font-weight:600}.rest-input{width:100%;padding:10px;background:#141b16;color:var(--text);border:1px solid var(--border);border-radius:7px}.offline-voice-filter{display:flex;gap:8px;align-items:center;font-size:14px;margin-top:15px}.offline-voice-filter input{accent-color:var(--green)}.history-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.history-summary article{min-width:0}.weekly-chart{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));align-items:end;gap:12px;margin:25px 0 35px;padding:22px;background:var(--panel);border:1px solid var(--border);border-radius:12px}.weekly-day{text-align:center;font-size:14px}.weekly-bar{background:#4b6938;color:white;border-radius:5px 5px 0 0;min-height:24px;margin-bottom:9px;display:flex;justify-content:center;align-items:center}.progress-title{font-size:22px}#offline-progress{display:block;margin-top:10px}@media(max-width:700px){.history-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.weekly-chart{gap:5px;padding:14px}.weekly-day{font-size:12px}.history-summary strong{font-size:28px}}
''';p.write_text(s,encoding='utf-8')
