import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/Gaurav Kumar/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await mkdir('qa',{recursive:true});await page.screenshot({path:'qa/desktop.png',fullPage:true});
for(const key of ['squat','curl','pushup','plank','press','pullup']){
 await page.locator(`[data-exercise="${key}"]`).click();await page.locator('#start-demo').click();await page.waitForTimeout(4800);const result=await page.locator('#reps').innerText();if(Number(result)<1)throw Error(key+' did not count');await page.locator('#pause').click();const before=await page.locator('#reps').innerText();await page.waitForTimeout(300);if(await page.locator('#reps').innerText()!==before)throw Error('pause');await page.locator('#finish').click();console.log(key,result);
}
await page.locator('[data-view="history"]').click();if(await page.locator('#history-body tr').count()!==6)throw Error('history');await page.reload();await page.locator('[data-view="history"]').click();if(await page.locator('#history-body tr').count()!==6)throw Error('persist');await page.locator('[data-view="coach"]').click();
await page.locator('#offline-save').click();await page.waitForFunction(()=>document.querySelector('#offline-status').textContent.includes('ready'),{},{timeout:60000});await context.setOffline(true);await page.reload();await page.waitForSelector('#start-demo');
for(const key of ['squat','curl','pushup','plank','press','pullup']){await page.locator(`[data-exercise="${key}"]`).click();await page.locator('#guide-video').evaluate(v=>v.play());await page.waitForTimeout(250);const ok=await page.locator('#guide-video').evaluate(v=>v.currentTime>0&&!v.error);if(!ok)throw Error('offline video '+key);}
const model=await page.evaluate(async()=>{const {FilesetResolver,PoseLandmarker}=await import('./vendor/vision_bundle.mjs');const files=await FilesetResolver.forVisionTasks('./vendor/wasm');const model=await PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'./vendor/pose_landmarker_lite.task',delegate:'CPU'},runningMode:'VIDEO',numPoses:1});model.close();return true;});console.log('offline model',model);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('mobile overflow');
await writeFile('qa/results.json',JSON.stringify({errors,offlineModel:model,offlineVideos:6,history:6,mobileOverflow:overflow},null,2));await browser.close();if(errors.length)throw Error(errors.join('\n'));
